# An array is a data structure which stores the values of the same type.

In [83]:
import numpy as np   # NumPy is a Python Library that provides arrays

# Generating one-dimensional (1D) array.

In [84]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

In [85]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Generating two-dimensional (2D) array.

In [86]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [87]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Checking the shape (dimension) and size of the array.

In [88]:
a.shape

(10,)

In [89]:
b.shape

(3, 3)

In [90]:
a.size

10

In [91]:
b.size

9

# Check the type

In [92]:
type(a)             # Type of data structure

numpy.ndarray

In [93]:
type(b)

numpy.ndarray

In [94]:
a.dtype             # dtype means data type. The type of a value i.e integer or float.

dtype('int64')

In [95]:
b.dtype

dtype('int64')

# Maximum and Minimum values

In [96]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

In [97]:
np.max(a)

9

In [98]:
np.min(a)

0

# Index of maximum and minimum values

In [99]:
a = np.array([4,2,3,13,5,7,14])

In [100]:
max(a)

14

In [101]:
a.max()    # finding maximum value

14

In [102]:
a.argmax() # index of maximum value

6

In [103]:
a.min()  # finding minimum value

2

In [104]:
a.argmin() # index of minimum value

1

# arange

In [105]:
c = np.arange(0,10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
d = np.arange(0,11,2)
d

array([ 0,  2,  4,  6,  8, 10])

In [108]:
e = np.arange(0,101,20)
e

array([  0,  20,  40,  60,  80, 100])

# linspace

In [109]:
x1 = np.linspace(0,20,5)
x1

array([ 0.,  5., 10., 15., 20.])

In [110]:
x2 = np.linspace(0,10,3)

In [111]:
x2

array([ 0.,  5., 10.])

In [112]:
x3 = np.linspace(0,10,50)

In [113]:
x3

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [114]:
x3.shape

(50,)

# reshape

In [115]:
y = np.arange(0,25)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [116]:
y.shape

(25,)

In [117]:
y.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [118]:
y.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [119]:
y.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

# zeros and ones

In [120]:
np.zeros(3)

array([0., 0., 0.])

In [121]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [122]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [123]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [124]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [125]:
7 * np.ones((3,3))

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

# eye, generating Identity matrix

In [126]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Random Numbers

## randn 

In [127]:
x1 = np.random.randn(3,3)                    # will generate random numbers from normal distribution.
x1

array([[-0.52069484,  1.21112839,  1.64393692],
       [-0.29521152, -1.51757553,  0.06068258],
       [-0.62792329,  0.66464695,  2.16451123]])

## rand

In [128]:
x2 = np.random.rand(3,3)                          # will generate random numbers between 0 and 1.
x2

array([[0.08842678, 0.62905445, 0.51501909],
       [0.36718481, 0.3415677 , 0.79302875],
       [0.21578951, 0.98172221, 0.82669451]])

## randint

In [129]:
x3 = np.random.randint(3,8,10)                  # will generate 10 random integers between 3 and 8.
x3

array([6, 4, 6, 6, 7, 3, 7, 5, 6, 6])

# Indexing and Slicing

## Indexing and slicing with 1D array

In [130]:
ar = np.array([4,2,3,13,5,7,14])
ar

array([ 4,  2,  3, 13,  5,  7, 14])

In [131]:
ar[3]  # Indexing

13

In [132]:
ar[6]

14

In [133]:
ar[1:4]  # Slicing

array([ 2,  3, 13])

In [134]:
ar[-1]  # Extracting last member of array.

14

In [135]:
ar[-2] # Extracting second last memeber of array

7

In [136]:
ar[1:]  # Slicing from index 1 to end.

array([ 2,  3, 13,  5,  7, 14])

In [137]:
ar[:4]  # slicing upto index 3

array([ 4,  2,  3, 13])

In [138]:
ar[:-1]  # Include everything except the last member of array

array([ 4,  2,  3, 13,  5,  7])

In [139]:
ar[::-1]  # Reversing or flipping the array

array([14,  7,  5, 13,  3,  2,  4])

## Indexing of sub-array and sub-matrix from 2D (matrix) array 

In [140]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [141]:
arr[0] # Extracting first row

array([1, 2, 3, 4])

In [142]:
arr[3] # Extracting last row

array([13, 14, 15, 16])

In [143]:
arr[2][1]

10

In [144]:
arr[2,1] # Other method

10

In [145]:
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [146]:
arr[:,3]   # Extracting last column

array([ 4,  8, 12, 16])

In [147]:
arr[:,3].reshape(-1,1)  # Extracting last column vertically

array([[ 4],
       [ 8],
       [12],
       [16]])

In [148]:
arr[:,3:]  # Other way of Extracting last column vertically

array([[ 4],
       [ 8],
       [12],
       [16]])